const SERVICE_BLOCKS: Record<string, (project: string) => string> = {
  nodejs: (p) => `  ${p}-app:
    image: node:20-alpine
    container_name: ${p}-app
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["node", "server.js"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped`,

  python: (p) => `  ${p}-app:
    image: python:3.12-slim
    container_name: ${p}-app
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["gunicorn", "wsgi:app", "-b", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped`,

  nextjs: (p) => `  ${p}-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${p}-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped`,

  react: (p) => `  ${p}-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${p}-frontend
    ports:
      - "80:80"
    restart: unless-stopped`,

  postgresql: (p) => `  ${p}-db:
    image: postgres:16-alpine
    container_name: ${p}-postgres
    volumes:
      - ${p}_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: \${POSTGRES_DB:-${p}}
      POSTGRES_USER: \${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5`,

  mysql: (p) => `  ${p}-db:
    image: mysql:8.0
    container_name: ${p}-mysql
    volumes:
      - ${p}_mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: \${MYSQL_DB:-${p}}
      MYSQL_USER: \${MYSQL_USER:-admin}
      MYSQL_PASSWORD: \${MYSQL_PASSWORD:-changeme}
      MYSQL_ROOT_PASSWORD: \${MYSQL_ROOT_PASSWORD:-rootpass}
    ports:
      - "3306:3306"
    restart: unless-stopped`,

  redis: (p) => `  ${p}-cache:
    image: redis:7-alpine
    container_name: ${p}-redis
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - ${p}_redis_data:/data
    restart: unless-stopped`,

  mongodb: (p) => `  ${p}-mongo:
    image: mongo:7
    container_name: ${p}-mongo
    volumes:
      - ${p}_mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: \${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: \${MONGO_PASSWORD:-changeme}
    ports:
      - "27017:27017"
    restart: unless-stopped`,

  nginx: (p) => `  ${p}-nginx:
    image: nginx:alpine
    container_name: ${p}-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped`,
};

const VOLUME_KEYS: Record<string, string> = {
  postgresql: "_pg_data",
  mysql: "_mysql_data",
  redis: "_redis_data",
  mongodb: "_mongo_data",
};

export function generateDockerCompose(projectName: string, services: string[]): string {
  const p = (projectName || "myapp").toLowerCase().replace(/[^a-z0-9]/g, "");
  const blocks = services.map((s) => SERVICE_BLOCKS[s]?.(p) ?? "").filter(Boolean);
  const volumes = services
    .filter((s) => VOLUME_KEYS[s])
    .map((s) => `  ${p}${VOLUME_KEYS[s]}:`);

  return `# Generated by MS Portfolio DevOps Toolkit
# Docker Compose config for ${p}

version: "3.9"

services:
${blocks.join("\n\n")}
${volumes.length > 0 ? `\nvolumes:\n${volumes.join("\n")}\n` : ""}
networks:
  default:
    name: ${p}-network
    driver: bridge
`;
}
