export type GHAConfig = {
  projectName: string;
  language: "node" | "python" | "go" | "java" | "docker";
  steps: string[];
  dockerImage?: string;
  deployTarget?: "ec2" | "ecs" | "k8s" | "none";
  awsRegion?: string;
};

const SETUP_STEPS: Record<string, string> = {
  node: `      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci`,

  python: `      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r requirements.txt`,

  go: `      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Download modules
        run: go mod download`,

  java: `      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build with Maven
        run: mvn -B package --file pom.xml`,

  docker: "",
};

const STEP_SNIPPETS: Record<string, string> = {
  lint: `
      - name: Lint
        run: npm run lint`,

  test: `
      - name: Run tests
        run: npm test`,

  build: `
      - name: Build
        run: npm run build`,

  "docker-build": `
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: \${{ secrets.DOCKERHUB_USERNAME }}
          password: \${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: \${{ secrets.DOCKERHUB_USERNAME }}/\${{ github.event.repository.name }}:latest,\${{ secrets.DOCKERHUB_USERNAME }}/\${{ github.event.repository.name }}:\${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max`,

  "deploy-ec2": `
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: \${{ secrets.EC2_HOST }}
          username: \${{ secrets.EC2_USER }}
          key: \${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull \${{ secrets.DOCKERHUB_USERNAME }}/\${{ github.event.repository.name }}:latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:3000 --restart unless-stopped \\
              \${{ secrets.DOCKERHUB_USERNAME }}/\${{ github.event.repository.name }}:latest`,

  "deploy-ecs": `
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: \${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          service: \${{ github.event.repository.name }}-service
          cluster: production
          wait-for-service-stability: true`,

  "deploy-k8s": `
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Kubernetes
        run: |
          echo "\${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yml
          export KUBECONFIG=kubeconfig.yml
          kubectl set image deployment/app app=\${{ secrets.DOCKERHUB_USERNAME }}/\${{ github.event.repository.name }}:\${{ github.sha }}
          kubectl rollout status deployment/app`,
};

export function generateGithubActions(c: GHAConfig): string {
  const setup = SETUP_STEPS[c.language] ?? "";
  const stepBlocks = c.steps.map((s) => STEP_SNIPPETS[s] ?? "").filter(Boolean).join("");

  return `# Generated by MS Portfolio DevOps Toolkit
# GitHub Actions CI/CD for ${c.projectName || "my-app"}

name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  NODE_ENV: production

jobs:
  ci-cd:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
${setup ? "\n" + setup : ""}${stepBlocks}
`;
}
