export type NginxConfig = {
  domain: string;
  backend: string;
  enableSSL: boolean;
  mode: "reverse-proxy" | "static" | "load-balance";
  enableCache: boolean;
  upstreams: string[];
  webroot: string;
};

export function generateNginxConfig(c: NginxConfig): string {
  const domain = c.domain || "example.com";
  const backend = c.backend || "localhost:3000";
  const upstreams = c.upstreams.filter(Boolean);

  const upstreamBlock =
    c.mode === "load-balance" && upstreams.length > 0
      ? `upstream backend {\n${upstreams.map((u) => `    server ${u};`).join("\n")}\n}\n\n`
      : "";

  const proxyTarget = c.mode === "load-balance" ? "http://backend" : `http://${backend}`;

  const locationBlock =
    c.mode === "static"
      ? `    root ${c.webroot || "/var/www/html"};
    index index.html;
    try_files $uri $uri/ =404;`
      : `    proxy_pass ${proxyTarget};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;`;

  const cacheDirective = c.enableCache
    ? `    proxy_cache_valid 200 1d;\n    add_header X-Cache-Status $upstream_cache_status;\n`
    : "";

  const httpRedirect = c.enableSSL
    ? `server {
    listen 80;
    listen [::]:80;
    server_name ${domain} www.${domain};
    return 301 https://$host$request_uri;
}

`
    : "";

  const listenDirective = c.enableSSL
    ? `    listen 443 ssl http2;\n    listen [::]:443 ssl http2;`
    : `    listen 80;\n    listen [::]:80;`;

  const sslBlock = c.enableSSL
    ? `\n    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;\n`
    : "";

  const cachePathBlock = c.enableCache && c.mode !== "static"
    ? `proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=app_cache:10m max_size=1g inactive=60m use_temp_path=off;\n\n`
    : "";

  return `# Generated by MS Portfolio DevOps Toolkit
# Nginx ${c.mode === "load-balance" ? "Load Balancer" : c.mode === "static" ? "Static File Server" : "Reverse Proxy"} config for ${domain}

${cachePathBlock}${upstreamBlock}${httpRedirect}server {
${listenDirective}
    server_name ${domain} www.${domain};
${sslBlock}
    # Logging
    access_log /var/log/nginx/${domain}.access.log;
    error_log  /var/log/nginx/${domain}.error.log;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location / {
${locationBlock}
${cacheDirective}    }
}
`;
}
